### ISSUE TITLE
komentarze w kodzie piszę się w języku angielskim

### ISSUE THREAD

**Issue by ghost** [rzuf-cpp/distro-chooser-2000#1]
linia 19 w pliku main,cpp 
    //wiem ?e kalecze angielski

**Comment by rzuf-cpp** [comment]
już poprawiłem

**Comment by LamaPolska** [comment]
nieeeeeeeeeeeeee

**Comment by ghost** [comment]
jeżeli już odpowiedziałeś na pytanie to zakącz ten wątek

**Comment by ghost** [comment]
ja już to zrobiłem

**Comment by Ketok4321** [comment]
wow
